const list = [
    {
      id: 1,
      title: "Protein Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 2,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 3,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 4,
      title: "Powder",
      description:"Whey protein powder",
      price: 89,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 5,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 6,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 7,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 8,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 9,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 10,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 11,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    {
      id: 12,
      title: "Powder",
      description:"Whey protein powder",
      price: 1890,
      img: "/Images/abhishek.JPG",
      amount: 1,
    },
    
];

export default list;